language: ruby
rvm:
#  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
#  - ree

script:
  - bundle exec rake spec
  - bundle exec rake test

notifications:
  email:
    recipients:
      - andre@programmerq.eu
    on_success: always
    on_failure: always